apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: qemu-rpi-os-lite
  name: qemu-rpi-os-lite
spec:
  ports:
    - name: "5022"
      port: 5022
      targetPort: 5022
  selector:
    io.kompose.service: qemu-rpi-os-lite
status:
  loadBalancer: {}
